name: Deploy React + Node App with MongoDB

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install frontend deps and build
      run: |
        cd client
        npm install
        npm run build

    - name: Install dependencies and build
  run: |
    npm install
    npm run build


    - name: Copy files to server (VPS)
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/ubuntu/chat-app"

    - name: Run server on remote via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/chat-app/server
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
          npm install
          pm2 start server.js || pm2 restart server.js
