jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install frontend dependencies
      run: |
        cd client
        npm install
        npm run build

    - name: Install backend dependencies
      run: |
        cd server
        npm install

    - name: Deploy to VPS/EC2 using SSH
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./"
        target: "/home/ubuntu/myapp"

    - name: Run Node server on EC2 (PM2)
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/myapp/server
          npm install
          pm2 restart server.js || pm2 start server.js
